name: carbon
description: IBM Carbon Design System for Flutter
version: 0.0.1
homepage: https://github.com/NourEldinShobier/carbon-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  vector_math: ^2.1.0
  flutter_svg: ^0.22.0
  pmvvm: ^2.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/svg/
    - assets/svg/notification/

  fonts:
    - family: IBMPlexSans-Thin
      fonts:
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
    - family: IBMPlexSans-ExtraLight
      fonts:
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
    - family: IBMPlexSans-Light
      fonts:
        - asset: assets/fonts/IBMPlexSans-Light.ttf
    - family: IBMPlexSans-Regular
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
    - family: IBMPlexSans-Medium
      fonts:
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
    - family: IBMPlexSans-SemiBold
      fonts:
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
    - family: IBMPlexSans-Bold
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf

    # icons

    - family: CIcons
      fonts:
        - asset: assets/carbon_icons/icons.ttf
